#!/bin/bash

PWD=`pwd | sed "s/$USER/dev/g" | sed 's/\/Users/\/home/'`
CMD=${@:-bash}
docker run -it \
    -v $HOME/workspace:/home/dev/workspace \
    -v $HOME/.ssh:/home/dev/.ssh \
    -v /var/run/screen \
    dev sh -c "exec >/dev/tty 2>/dev/tty </dev/tty && cd $PWD && exec $CMD"
# This exec tty stuff is so screen will run in the container.
# See https://github.com/docker/docker/issues/728
